name: my-workflow

on:
  push:
    branches:
      - honojs  # Adjust the branch as needed

jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Execute bun index.ts
        run: bun src/index.ts

      - name: Build
        run: bun run build

