name: my-workflow

on:
  push:
    branches:
      - honojs # Adjust the branch as needed

jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Specify the Node.js version you need

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Execute bun index.ts
        run: bun src/index.ts
      - name: Execute bun index.ts
        run: bun run prisma generate

      - name: Build
        run: bun run build
